name: Simple 3-Env CD

on:
  push:
    branches: [ main ]         
  workflow_dispatch:           

permissions:
  contents: read

jobs:
  build:
    name: Build once
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare artifact
        run: |
          mkdir -p artifact
          cp app/index.txt artifact/index.txt
          echo "Build time: $(date)" >> artifact/index.txt
          cat artifact/index.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: artifact/

  deploy_dev:
    name: Deploy to Dev (no approvals)
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: dev                   
    steps:
      - uses: actions/checkout@v4         
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: artifact

      - name: Show artifact
        run: cat artifact/index.txt

      - name: Deploy to dev
        env:                       
          DB_USER: ${{ secrets.DB_USER }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "Connecting to DB: $DB_SERVER with user: $DB_USER"
          ./scripts/deploy.sh dev artifact/index.txt

  deploy_uat:
    name: Deploy to UAT (requires approval)
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment:
      name: uat                   
    steps:
      - uses: actions/checkout@v4          
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: artifact

      - name: Deploy to uat
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "Connecting to DB: $DB_SERVER with user: $DB_USER"
          ./scripts/deploy.sh uat artifact/index.txt

  deploy_prod:
    name: Deploy to Prod (requires approval)
    runs-on: ubuntu-latest
    needs: deploy_uat
    environment:
      name: prod                 

    steps:
      - uses: actions/checkout@v4          
      - uses: actions/download-artifact@v4
        with:
          name: app-build
          path: artifact

      - name: Deploy to prod
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: |
          echo "Connecting to DB: $DB_SERVER with user: $DB_USER"
          ./scripts/deploy.sh prod artifact/index.txt
